### ISSUE TITLE
Unity Version ?

### ISSUE THREAD

**Issue by araffin** [r7vme/learning-to-drive-in-a-day#3]
Hello,

Thanks for this nice project (and kudos for using stable-baselines ;) ).
I tried to run your code but I have some issues:

With docker:
```
./run-in-docker.sh 
starting DonkeyGym env
Missing DONKEY_SIM_PORT environment var. Using defaults
donkey subprocess started
binding to ('0.0.0.0', 9090)
waiting to load..
No protocol specified
No protocol specified
Error initializing Gtk+
No protocol specified
waiting to load..
```
I have intel graphics but the problem is still here even when removing `device=/dev/dri:/dev/dri`

In a conda env: 
Everything starts properly except that I got this error message in the terminal:
```
Expecting property name enclosed in double quotes: line 1 column 67 (char 66) failed to read json  {"msg_type":"telemetry","steering_angle":0,"throttle":0 ...
```

Trying the scripts from the sdsandbox repo, I ran into the same issue (see https://github.com/tawnkramer/sdsandbox/issues/11), so I assume the problem comes from my Unity version that may be too recent.
What version are you using?

System Info:
- python 3.6
- Unity-2018.2.7f1
- requirements installed via `pip -r requirements.txt`

**Comment by araffin** [comment]
In fact, the problem may comes from donkey_gym, I am working on a patch ;)

Looking at the data received, it may comes from the fact that I am using a french computer, so it seems that unity represents float in the French notation (e.g. 2,3 instead of 2.3) which create invalid json.

cf the speed here:
```
Expecting property name enclosed in double quotes: line 1 column 67 (char 66) failed to read json  {"msg_type":"telemetry","steering_angle":0,"throttle":0,"speed":0,0004571025,
```

see: https://forum.unity.com/threads/decimal-separator-randomly-becoming-something-that-looks-like-a-comma.257708/


The patch:

```python
def replace_float_notation(string):
	regex_french_notation = r'"[a-zA-Z_]+":(?P<num>[0-9,E-]+),'
	regex_end = r'"[a-zA-Z_]+":(?P<num>[0-9,E-]+)}'

	for regex in [regex_french_notation, regex_end]:
		matches = re.finditer(regex, string, re.MULTILINE)

		for match in matches:
			start, end = match.start('num'), match.end('num')
			num = match.group('num').replace(',', '.')
			string = string.replace(match.group('num'), num)
	return string
```

**Comment by araffin** [comment]
Update: with the patch, it is working fine, so I can begin experiments now ;)

**Comment by zhangjunwang** [comment]
I have the same problem with you.
Could you tell me how can i add this patch?
Thanks!

**Comment by zhangjunwang** [comment]
@araffin

**Comment by araffin** [comment]
@zhangjunwang You can find it here https://github.com/araffin/donkey_gym/blob/master/donkey_gym/core/tcp_server.py

**Comment by XJTUWYD** [comment]
> @zhangjunwang You can find it here https://github.com/araffin/donkey_gym/blob/master/donkey_gym/core/tcp_server.py

hello,Could you tell me where did I use this funtion? thanks!

**Comment by XJTUWYD** [comment]
> > @zhangjunwang You can find it here https://github.com/araffin/donkey_gym/blob/master/donkey_gym/core/tcp_server.py
> 
> hello,Could you tell me where did I use this funtion? thanks!

@araffin
